### ISSUE TITLE
 assert _HAS_FFMPEG, “Cannot find installation of ffmpeg.”

### ISSUE THREAD

**Issue by DIpakbhagat26** [creotiv/object_detection_projects#1]
Hi,

I have installed all the dependencies and when I am tried to execute the program I am stuck on an error. I did some google but didn’t find any update. can You please help me in this.

The error is

File “C:\Users\Deepu\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py”, line 240, in vreader
 assert _HAS_FFMPEG, “Cannot find installation of ffmpeg.”
AssertionError: Cannot find installation of ffmpeg.

**Comment by creotiv** [comment]
You need to install ffmpeg library https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg
