### ISSUE TITLE
Do I need a GPU to run this code?

### ISSUE THREAD

**Issue by FelipeMiranda** [creotiv/object_detection_projects#2]
It fails on tensorflow-gpu, can't I just remove it?

**Comment by creotiv** [comment]
right now, no you don't, so you can remove it. Basically if you dont have a GPU then install tensorflow only

**Comment by FelipeMiranda** [comment]
Thank you creotiv, I did that and it is working, now I can`t figure out how to use an RTSP stream, could you help me with that?

**Comment by creotiv** [comment]
https://stackoverflow.com/questions/20891936/rtsp-stream-and-opencv-python
