### ISSUE TITLE
Won't open window

### ISSUE THREAD

**Issue by lumbulliqi** [creotiv/object_detection_projects#9]
The script traffic.py won't open the winodw of video. Just it excecutes on console/terminal.

**Comment by creotiv** [comment]
it shouldn't open any windows

**Comment by lumbulliqi** [comment]
The window of https://cdn-images-1.medium.com/max/1000/1*kFbuhpNtiUFUU0nL2n5NLA.png

**Comment by creotiv** [comment]
it's not a window, it's inference, video vizualization created from frames.

**Comment by lumbulliqi** [comment]
sir, I respect your job but can you help me and sry for my english

how to open that picture that i sad https://cdn-images-1.medium.com/max/1000/1*kFbuhpNtiUFUU0nL2n5NLA.png

**Comment by creotiv** [comment]
Here is docs: https://github.com/creotiv/object_detection_projects/tree/master/opencv_traffic_counting
you need to use Visualizer(image_dir=IMAGE_DIR) in pipeline, which will save all images with vizualization to IMAGE_DIR folder(create it before run). 

To create video from images you need to install ffmpeg:
sudo apt-get install ffmpeg

and then go to your IMAGE_DIR and run
ffmpeg -start_number 0 -framerate 15 -i ./processed_%04d.png -s:v 1280:720 -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p ./out.mp4

this will create out.mp4 video

**Comment by lumbulliqi** [comment]
Thank you, good job (Y)
